export const browserCoreExamples = [
  "autolab browser status",
  "autolab browser start",
  "autolab browser stop",
  "autolab browser tabs",
  "autolab browser open https://example.com",
  "autolab browser focus abcd1234",
  "autolab browser close abcd1234",
  "autolab browser screenshot",
  "autolab browser screenshot --full-page",
  "autolab browser screenshot --ref 12",
  "autolab browser snapshot",
  "autolab browser snapshot --format aria --limit 200",
  "autolab browser snapshot --efficient",
  "autolab browser snapshot --labels",
];

export const browserActionExamples = [
  "autolab browser navigate https://example.com",
  "autolab browser resize 1280 720",
  "autolab browser click 12 --double",
  'autolab browser type 23 "hello" --submit',
  "autolab browser press Enter",
  "autolab browser hover 44",
  "autolab browser drag 10 11",
  "autolab browser select 9 OptionA OptionB",
  "autolab browser upload /tmp/autolab/uploads/file.pdf",
  'autolab browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "autolab browser dialog --accept",
  'autolab browser wait --text "Done"',
  "autolab browser evaluate --fn '(el) => el.textContent' --ref 7",
  "autolab browser console --level error",
  "autolab browser pdf",
];
